const theme = {
    light: {
        theme: 'light',
        bg: '#FFFFFF',
        bg2: '#FFF3E8',
        bg3: '#FFFFFF',
        txt: '#212121',
        txt2: '#424242',
        txt3: '#757575',
        disable: '#9E9E9E',
        disable1: '#E0E0E0',
        disable3: '#616161',
        border: '#EEEEEE',
        icon: '#BDBDBD',
        input: '#F5F5F5',
        input2: '#FAFAFA',
        input3: '#FAFAFA',
        bottom: '#FFFFFF',

        s: '#FF8216',
        // g:require('../../assets/image/g.png'),
        bar: require('../../assets/image/bar.png'),
        bar1: require('../../assets/image/bar1.png'),
        master: require('../../assets/image/master.png'),
    },
    dark: {
        theme: 'dark',
        bg: '#181A20',
        bg2: '#35383F',
        bg3: '#1F222A',
        txt: '#FFFFFF',
        txt2: '#E0E0E0',
        txt3: '#757575',
        disable: '#616161',
        disable1: '#35383F',
        disable3: '#E0E0E0',
        border: '#35383F',
        icon: '#757575',
        input: '#1F222A',
        input2: '#181A20',
        input3: '#1F222A',
        bottom: '#181A20',

        s: '#FFFFFF',
        // g:require('../../assets/image/gd.png'),
        bar: require('../../assets/image/bard.png'),
        bar1: require('../../assets/image/bar1d.png'),
        master: require('../../assets/image/masterd.png'),
    },

};

export default theme;